version: '3.8'

services:
  backend:
    build:
      context: ./rooming-list-api
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rooming_list_app
      - JWT_SECRET=supersecretkey
    volumes:
      - ./rooming-list-api:/app
    restart: unless-stopped

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rooming_list_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  frontend:
    build:
      context: ./rooming-list-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
